### ISSUE TITLE
Error on a linux localhost server (lampp) but works on a windows localhost server (wamp))

### ISSUE THREAD

**Issue by Chikwanda420** [neuharthr/Fleetco#3]
**Warning**: Undefined array key "language" in /opt/lampp/htdocs/fleetco/include/commonfunctions.php on line 3517

**Deprecated**: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /opt/lampp/htdocs/fleetco/include/commonfunctions.php on line 3517

**Warning**: Undefined array key "myqsladdress" in /opt/lampp/htdocs/fleetco/connections/MySQLiConnection.php on line 64

Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'fleetco'@'localhost' (using password: YES) in /opt/lampp/htdocs/fleetco/connections/MySQLiConnection.php:73 Stack trace: #0 /opt/lampp/htdocs/fleetco/connections/MySQLiConnection.php(73): mysqli_connect('127.0.0.1', 'fleetco', ''', '3306') #1 /opt/lampp/htdocs/fleetco/connections/Connection.php(55): MySQLiConnection->connect() #2 /opt/lampp/htdocs/fleetco/connections/MySQLiConnection.php(21): Connection->__construct(Array) #3 /opt/lampp/htdocs/fleetco/connections/ConnectionManager.php(167): MySQLiConnection->__construct(Array) #4 /opt/lampp/htdocs/fleetco/connections/ConnectionManager.php(84): ConnectionManager->getConnection('carrier_at_loca...') #5 /opt/lampp/htdocs/fleetco/connections/ConnectionManager.php(95): ConnectionManager->byId('carrier_at_loca...') #6 /opt/lampp/htdocs/fleetco/include/appsettings.php(1145): ConnectionManager->getDefault() #7 /opt/lampp/htdocs/fleetco/include/dbcommon.php(57): include('/opt/lampp/htdo...') #8 /opt/lampp/htdocs/fleetco/RenewalsMaster_add.php(5): require_once('/opt/lampp/htdo...') #9 {main} thrown in /opt/lampp/htdocs/fleetco/connections/MySQLiConnection.php on line 73

**Comment by gilesytheking** [comment]
I'm also having the same issue. I'm very interested to try this platform. @Chikwanda420 did you manage to resolve the issue?

**Comment by neuharthr** [comment]
Would either of you like to submit a PR for this?
